<h1 class="title"> Dicas para manter a saúde </h1>
    <div class="line"></div>
    
    <table>
        <tbody>
            
            
            
            <div class="item-page">
                <p style="text-align: justify;">
                    <span style="font-size: 13px!important;"> - Desfrutar da saúde mental significa ter uma sensação de bem-estar, sendo capaz de funcionar durante a vida todos os dias e se sentir confiante para subir para um desafio quando a oportunidade surgir.&nbsp;Assim como a sua saúde física, há ações que você pode tomar para aumentar a sua saúde mental.&nbsp;Aumente o seu bem-estar e fique mentalmente saudável, seguindo alguns passos simples.
                        <br><br> - Desenvolver e manter relações fortes com as pessoas ao seu redor  irá apoiar e enriquecer a sua vida.&nbsp;A qualidade dos nossos relacionamentos pessoais tem um grande efeito sobre nosso bem-estar.&nbsp;Colocar tempo e esforço para construir relacionamentos fortes podem trazer grandes recompensas.</span></p>
                <p style="text-align: justify;"><span style="font-size: 13px!important;"> - Participar e compartilhar interesses.</strong>&nbsp;Participe de um clube ou grupo de pessoas que compartilham seus interesses.&nbsp;Ser parte de um grupo de pessoas com um interesse comum proporciona uma sensação de pertença e é bom para a sua saúde mental.&nbsp;Participe de um clube desportivo, uma banda, um grupo de caminhada à noite, uma aula de dança, um grupo de teatro ou coro, um livro ou um carro clube.</span></p>
                <p style="text-align: justify;"><span style="font-size: 13px!important;">  - Tire um tempo para desfrutar.</strong>&nbsp;Separe um tempo para as atividades, passatempos e projetos que você gosta.&nbsp;Fazer palavras cruzadas, fazer uma caminhada em seu parque local, ler um livro, costurar uma colcha de retalhos; tirar fotos com seus filhos, brincar com seus animais de estimação - o que leva a sua fantasia.</span></p>
                <p style="text-align: justify;"><span style="font-size: 13px!important;"> - Mire na meta: metas de resultados bem claras ajudam a não perder o foco e se manter firme nos treinos.</span></p>
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"> - Oferecer seu tempo para uma causa ou questão que você se preocupa.&nbsp;Ajude um vizinho, trabalhar em uma horta comunitária ou fazer algo agradável para um amigo.&nbsp;Há muitas formas de contribuir que podem ajudá-lo a se sentir bem sobre si mesmo e seu lugar no mundo.&nbsp;Um esforço para melhorar a vida dos outros é certo para melhorar sua vida também.</span></p>
                <p class="MsoNormal" style="text-align: justify;"> - Aproveite as baixas temperaturas para aumentar seu gasto calórico: no frio você pode aumentar em até 30% a perda de calorias, o que torna o período excelente para eliminar as gorduras, pois com as baixas temperaturas seu corpo gasta mais energia para se manter aquecido, isso acelera o metabolismo favorecendo a eliminação das indesejáveis gordurinhas.</span></p>
                <p class="MsoNormal" style="text-align: justify;"> - Atividades mais aeróbias: durante o inverno você apostar pelas aulas de dança, ginástica e treino em circuito, que aquecem mais rápido o corpo e te mantém quentinha por um período maior. Vai dar tempo de tomar o banho e colocar a roupa sem passar frio!.</span></p>
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"> - Esteja ciente de que desencadeia o estresse e como você reage.&nbsp;Você pode ser capaz de evitar alguns dos gatilhos e aprender a preparar ou administrar outros.&nbsp;O estresse é uma parte da vida e afeta as pessoas de diferentes maneiras.&nbsp;Ele só se torna um problema quando ele faz você se sentir desconfortável ou angustiado.&nbsp;Um estilo de vida equilibrada pode ajudar a gerir melhor o stress.&nbsp;Se você tiver problemas para o encerramento, você pode achar que a respiração de relaxamento, yoga ou meditação pode ajudar.&nbsp;</span></p>
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"> - Começar a abundância do sono.&nbsp;Vá para a cama em um horário regular de cada dia e praticar bons hábitos para dormir melhor&nbsp;.&nbsp;Sono restaura tanto o corpo e a mente.&nbsp;No entanto, a sensação de fadiga ainda pode definir se você se sente constantemente apressado e sobrecarregado quando você está acordado.</span></p>
               <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"> - Escolha uma modalidade que seja prazerosa. Determine um horário certo para ir à academia, tornando a atividade física um hábito que integra a sua rotina. Trace metas para atingir seu objetivo. Se quiser, por exemplo, perder 5 quilos até as férias, determine o quanto deverá perder por mês para chegar ao peso ideal. Dê preferência para atividades dinâmicas ou feitas em grupos. Procure estímulos. Ter uma companhia ajuda a manter o compromisso com a atividade física.</span></p>
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"> - Tome um momento para observar cada um de seus sentidos a cada dia.&nbsp;Simplesmente "ser" no momento - sentir o sol e o vento em seu rosto e perceber o ar que você está respirando.&nbsp;É fácil ser pego pensando sobre o passado ou o planejamento para o futuro em vez de viver o presente.&nbsp;Praticar a atenção plena, focando sua atenção em estar no momento, é uma boa maneira de fazer isso.&nbsp;Fazendo um esforço consciente para estar ciente de seu mundo interior e exterior é importante para sua saúde mental.</span></p> 
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"> - Isso pode ser tão simples como pedir a um amigo para tomar conta enquanto você tem algum tempo ou falar com o seu médico sobre onde encontrar um conselheiro ou serviço de saúde mental comunitária.&nbsp;A vida perfeita e livre de preocupações não existe. Jornada de vida de toda a gente tem pedaços irregulares e as pessoas ao seu redor podem ajudar.&nbsp;Se você não obter a ajuda que você precisa em primeiro lugar, continuar pedindo até que você faça.</span></p> 

            </div>
        </tbody>
    </table>
    <div id="footer">
      
    </div>
