<h1 class="title">A Academia</h1>
    <div class="line"></div>
    
    <table>
        <tbody>
            <div class="item-page">
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;">A </span><span style="font-size: 13px; line-height: 1.3em;">academia</span><span style="font-size: 13px; line-height: 1.3em;"> NetFitness &nbsp;atua há vinte e dois anos, no Recife, promovendo saúde e bem-estar aos seus clientes. Baseada na excelência, está sempre focando na qualidade e nos resultados, tanto nas atividades oferecidas quanto no atendimento personalizado ao seu público. Para isso, mantém uma metodologia própria e constante de capacitação da equipe de professores.</span></p>
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"> Na </span><span style="font-size: 13px; line-height: 1.3em;">academia</span><span style="font-size: 13px!important;"> NetFitness</span><span style="font-size: 13px!important;">, os treinos são elaborados de acordo com o perfil do aluno e os resultados que ele pretende atingir. A metodologia diferenciada da academia, onde a padronização dos exercícios facilita o acompanhamento de qualquer professor da </span><span style="font-size: 13px!important;"><span style="font-size: 13px!important;"><span style="font-size: 13px!important;">academia </span></span></span><span style="font-size: 13px; line-height: 16.899999618530273px;">NetFitness</span><span style="font-size: 13px; line-height: 1.3em;">, permite ao aluno atingir seus objetivos de forma saudável e no tempo certo.</span></p>
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"> <br>Outros diferenciais da </span><span style="font-size: 13px; line-height: 1.3em;">academia</span><span style="font-size: 13px!important;"> </span><span style="font-size: 13px!important;"><span style="font-size: 13px!important;">NetFitness</span>:</span></p>
                <p style="text-align: justify;"><span style="font-size: 13px!important;">• Academia com maior área verde do Recife;<br> • Segurança externa e interna em tempo integral;<br> • Atualização de equipamentos a cada dois anos; <br> • Ambientes com WI-FI;<br> • Treinamento ergométrico individualizado; <br> • Piscina aquecida em temperatura adequada. <br></span></p>
                <h3 style="text-align: justify;"><span style="font-size: 18px!important;">História</span></h3>
                <p style="text-align: justify;"><span style="font-size: 13px!important;">De um simples hobby à consolidação de um negócio bem estruturado, formado por profissionais competentes e especialistas. Essa é a história da antiga Companhia de Atletas, idealizada no ano de 1991, quando sua sócio-fundadora Rosi Egito ainda dava aulas de ginástica em casa. Com dedicação e visão empreendedora, a professora transformou seu projeto particular em uma academia de ginástica na Caxangá. Em 2013, foram iniciadas as atividades na Unidade Espinheiro, sendo uma academia renovada e moderna, com uma proposta totalmente nova e diferenciada.<br><br>Com o tempo, naturalmente, de Companhia de Atletas passou a se chamar Cia. Um nome curto e de fácil fixação. Sinônimo de presença. Presença de profissionais capacitados e companhia de outras pessoas com o mesmo objetivo: cuidar da saúde. Também carrega um outro significado, o de evolução de uma marca que está sempre em movimento e buscando o melhor para seus clientes. Por este motivo, no dia 1º de fevereiro de 2014, a Cia de Atletas passou a se chamar NetFitness!</span></p>
                <h3 style="text-align: justify;"><span style="font-size: 18px!important;">Nossa Missão</span></h3>
                <p style="text-align: justify;"><span style="font-size: 13px!important;">Trabalhar com dedicação e comprometimento para superar as expectativas dos nossos clientes através de serviços de FITNESS, promovendo bem-estar e qualidade de vida ao cidadão pernambucano.</span></p>
                <h3 style="text-align: justify;"><span style="font-size: 18px!important;">Nossos Valores</span></h3>
                <p style="text-align: justify;"><span style="font-size: 13px!important;"><strong>ÉTICA</strong> – Gerir os recursos com honestidade, integridade e idoneidade; respeito pelas pessoas, seus valores e sua individualidade; respeito pelo ambiente em que vivemos.</span></p>
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"><strong>SIMPLICIDADE</strong> – Adotar uma conduta simples e objetiva, sem comprometer a qualidade.</span></p>
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"><strong>COMPROMISSO COM RESULTADOS</strong> – Direcionar todos os nossos esforços para a geração de resultados satisfatórios à empresa e ao cliente.</span></p>
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"><strong>INOVAÇÃO</strong> – Analisar com frequência os ambientes externos e internos à academia, buscando inovar na oferta de processos e serviços para melhorar o atendimento ao cliente, e simplificando a relação empresa-público.</span></p>
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"><strong>VALORIZAÇÃO DO CONHECIMENTO</strong> – Determinar o conhecimento como fator essencial para o desenvolvimento da empresa, compartilhando-o entre os nossos profissionais.</span></p>
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"><strong>BOM-HUMOR</strong> - A pessoa bem humorada é mais descontraída perante situações potencialmente estressantes, e as compreende de forma mais flexível.</span></p>
                <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 13px!important;"><strong>HUMILDADE</strong> - A palavra humildade vem do latim humus, que indica o solo fértil. Diferente de autodepreciação. Reconhecer o valor do outro. Conhecimento do que somos e do que não somos. A virtude que torna todas as outras virtudes discretas.  A virtude do homem que sabe não ser Deus.</span></p> 
               </div>
        </tbody>
    </table>
    <div id="footer">
      
    </div>
